;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/VRE/Core/DefaultGameplayTags.DefaultGameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Car.small.blue",DevComment="")
+GameplayTagList=(Tag="Item.Green.Box",DevComment="")
+GameplayTagList=(Tag="Item.Red",DevComment="")
+GameplayTagList=(Tag="Item.Red.box",DevComment="")
+GameplayTagList=(Tag="Item.Yellow.box",DevComment="")
+GameplayTagList=(Tag="Zone.Table",DevComment="")

